Repository erda-project/docs, pull requests merged in 2021-09, with the labels that each got.

#33 feature: add faq about nfs and public kubernetes version
  docs/1.2/manual/faq/install.md
  package-lock.json
Labels: approved

#36 fix: newbie.md link error
  docs/1.2/manual/install/helm-install/helm-install-demo.md
  docs/1.2/manual/install/helm-install/helm-install-prod.md
  docs/1.2/manual/quick-start/newbie.md
Labels: approved

#35 add document example of loop configuration
  docs/1.2/manual/deploy/pipeline.md
  docs/1.2/manual/dop/guides/qa-and-testing/auto-test-getting-started.md
  docs/1.2/manual/dop/guides/reference/pipeline.md
Labels: approved

#38 add pipeline placeholder syntax
  docs/1.2/manual/dop/guides/reference/pipeline.md
Labels: approved

#37 feature: add log query syntax description
  docs/1.2/manual/msp/guides/log/query.md
Labels: msp

#39 feature: optimize install faq, add serial number
  docs/1.2/manual/faq/install.md
Labels: approved

#43 Update kubeprober introduction
  docs/1.2/manual/eco-tools/kubeprober/guides/introduction.md
Labels: approved

#48 Update introduction.md
  docs/1.3/manual/eco-tools/kubeprober/guides/introduction.md
Labels: approved

#47 Update pipeline.md
  docs/1.3/manual/dop/guides/reference/pipeline.md
Labels: approved

#45 Add api-drive-develop
  docs/.vuepress/sidebar/zh.js
  docs/1.3/manual/dop/best-practices/api-drive-develop.md
Labels: approved

#40 add comments to if configuration
  docs/1.2/manual/deploy/pipeline.md
  docs/1.2/manual/dop/guides/reference/pipeline.md
Labels: approved

#50 Feature: fix pipeline expression grammar issue
  docs/1.2/manual/deploy/pipeline.md
  docs/1.2/manual/dop/guides/reference/pipeline.md
Labels: approved

#49 Feature: update doc style
  docs/1.3/manual/about/intro.md
  docs/1.3/manual/faq/install.md
  docs/1.3/manual/install/docker-install.md
  docs/1.3/manual/install/helm-install/configuration.md
  docs/1.3/manual/install/helm-install/helm-install-demo.md
  docs/1.3/manual/install/helm-install/helm-install-prod.md
  docs/1.3/manual/install/helm-install/high-availability.md
  docs/1.3/manual/install/helm-install/introduction.md
  docs/1.3/manual/install/helm-install/premise.md
  docs/1.3/manual/install/helm-install/uninstall.md
  docs/1.3/manual/install/helm-install/upgrade.md
Labels: approved

#51 chore: build need more memory
  package.json
Labels: approved

#52 faq for install: add mysql issue when docker-compose
  docs/1.3/manual/faq/install.md
Labels: approved, install

#53 fix: add links to specific documents of faq.md
  docs/1.3/manual/.DS_Store
  docs/1.3/manual/faq/faq.md
Labels: approved

#55 feat: show tip when enter old version document
  docs/.vuepress/enhanceApp.js
  docs/.vuepress/styles/index.styl
  docs/.vuepress/theme/layouts/Layout.vue
  package-lock.json
  package.json
Labels: approved

#56 Feature: msp menu modification
  docs/1.3/manual/msp/concepts/apigw/arch.md
  docs/1.3/manual/msp/concepts/apigw/core.md
  docs/1.3/manual/msp/examples/apigw/access-limit.md
  docs/1.3/manual/msp/examples/apigw/cors.md
  docs/1.3/manual/msp/examples/apigw/custom-header.md
  docs/1.3/manual/msp/examples/apigw/rate-limit.md
  docs/1.3/manual/msp/examples/apm/exception-alert.md
  docs/1.3/manual/msp/examples/apm/service-dashboard.md
  docs/1.3/manual/msp/examples/apm/status-alert.md
  docs/1.3/manual/msp/examples/log/java-log-rule.md
  docs/1.3/manual/msp/guides/apm/alert-config.md
  docs/1.3/manual/msp/guides/apm/alert-custom.md
  docs/1.3/manual/msp/guides/apm/browser-monitor.md
  docs/1.3/manual/msp/guides/apm/dashboard.md
  docs/1.3/manual/msp/guides/apm/service-analysis.md
  docs/1.3/manual/msp/guides/apm/status.md
  docs/1.3/manual/msp/guides/apm/trace.md
  docs/1.3/manual/msp/guides/log/query.md
  docs/1.3/manual/msp/guides/log/rules.md
  docs/1.3/manual/msp/guides/platform/msp-overview.md
  docs/1.3/manual/msp/guides/platform/msp-project-list.md
  docs/1.3/manual/msp/guides/platform/msp-project.md
  docs/1.3/manual/msp/practice/apigw/apim.md
  docs/1.3/manual/msp/practice/log/log-to-diagnose-business-exception.md
  docs/1.3/manual/quick-start/premise.md
Labels: approved

#54 Fix: delete obsolete links
  docs/1.3/manual/dop/guides/reference/erda-yaml.md
  docs/1.3/manual/dop/guides/reference/pipeline.md
Labels: approved

#57 fix: notification not show in production mode
  docs/.vuepress/enhanceApp.js
  docs/.vuepress/styles/index.styl
  docs/.vuepress/theme/layouts/Layout.vue
  package-lock.json
  package.json
Labels: approved

#58 feat: keep only last 3 version docs
  README.md
  docs/.vuepress/get-ver.js
  docs/.vuepress/nav/zh.js
  docs/.vuepress/sidebar/vers/1.0.js
  docs/.vuepress/sidebar/vers/1.1.js
  docs/.vuepress/sidebar/vers/1.2.js
  docs/.vuepress/sidebar/vers/1.3.js
  docs/.vuepress/sidebar/zh.js
  package-lock.json
  package.json
Labels: approved

#60 Feature/add cmp docs
  docs/.vuepress/sidebar/vers/1.3.js
  docs/.vuepress/sidebar/zh.js
  docs/1.3/manual/cmp/concept.md
  docs/1.3/manual/cmp/example.md
  docs/1.3/manual/cmp/examples/check-env.md
  docs/1.3/manual/cmp/examples/check-workload.md
  docs/1.3/manual/cmp/examples/set-labels.md
  docs/1.3/manual/cmp/guide/alert/dashboard.md
  docs/1.3/manual/cmp/guide/alert/report.md
  docs/1.3/manual/cmp/guide/cluster/cluster-node-labels.md
  docs/1.3/manual/cmp/guide/cluster/k8s-dashboard.md
  docs/1.3/manual/cmp/practice/alert-config.md
  docs/1.3/manual/faq/install.md
  package-lock.json
Labels: approved

#62 Feature: dop doc modification
  docs/1.3/manual/dop/examples/deploy/deploy-from-caches-build.md
  docs/1.3/manual/dop/examples/deploy/deploy-from-git.md
  docs/1.3/manual/dop/examples/deploy/deploy-from-go-build.md
  docs/1.3/manual/dop/examples/deploy/deploy-from-image.md
  docs/1.3/manual/dop/examples/deploy/deploy-from-java-build.md
  docs/1.3/manual/dop/examples/deploy/manage-mirror.md
  docs/1.3/manual/dop/examples/deploy/nexus.md
  docs/1.3/manual/dop/examples/project-management.md
Labels: approved

#61 Feature: quick start doc modification
  docs/1.3/manual/install/helm-install/upgrade.md
  docs/1.3/manual/quick-start/newbie.md
Labels: approved

#63 Feature: update docs in cmp and dop
  docs/1.3/manual/cmp/examples/check-env.md
  docs/1.3/manual/cmp/examples/check-workload.md
  docs/1.3/manual/cmp/examples/set-labels.md
  docs/1.3/manual/dop/best-practices/microservice-springcloud.md
  docs/1.3/manual/dop/concepts/agile-info.md
  docs/1.3/manual/dop/concepts/iac.md
  docs/1.3/manual/dop/examples/deploy/deploy-from-git.md
  docs/1.3/manual/dop/examples/deploy/deploy-from-go-build.md
  docs/1.3/manual/dop/examples/deploy/deploy-from-image.md
  docs/1.3/manual/dop/examples/project-management.md
Labels: approved

#64 Feature/k8s dashborad
  docs/1.3/manual/cmp/guide/cluster-overview.md
  docs/1.3/manual/cmp/guide/cluster/k8s-dashboard.md
  package-lock.json
Labels: approved

#66 fix typo
  docs/1.3/manual/cmp/guide/cluster/k8s-dashboard.md
Labels: approved
