Repository erda-project/docs, pull requests merged in 2022-03, with the labels that each got.

#159 feat: Add alert center documentation
  docs/.vuepress/sidebar/vers/1.6.js
  docs/1.6/manual/msp/guides/apm/alert-center.md
Labels: approved

#160 feat: add deploy at best practices
  docs/.vuepress/sidebar/vers/1.6.js
  docs/1.6/manual/dop/best-practices/release.md
Labels: approved

#163 Create VERSION
  VERSION
Labels: approved

#162 service monitor and trace docs
  docs/.vuepress/sidebar/vers/1.5.js
  docs/1.6/manual/msp/guides/apm/dashboard-advanced.md
  docs/1.6/manual/msp/guides/apm/dashboard.md
  docs/1.6/manual/msp/guides/apm/service-monitor.md
  docs/1.6/manual/msp/guides/apm/service-overview.md
  docs/1.6/manual/msp/guides/apm/trace.md
Labels: approved

#165 feature: adjust msp menu
  docs/.vuepress/sidebar/vers/1.6.js
Labels: approved

#166 feat: modify alert-center file
  docs/1.6/manual/msp/guides/apm/alert-center.md
Labels: approved

#169 fix: add tips for java-build
  docs/1.6/manual/dop/examples/deploy/deploy-from-java-build.md
Labels: approved

#167 fix bugs in msp menu and release doc
  docs/.vuepress/sidebar/vers/1.5.js
  docs/.vuepress/sidebar/vers/1.6.js
  docs/1.6/manual/dop/guides/deploy/release.md
Labels: approved

#168 add docs
  docs/.vuepress/sidebar/vers/1.6-en.js
  docs/1.6/manual/dop/guides/deploy/release.md
  docs/en/1.6/manual/dop/guides/deploy/artifact-and-build.md
  docs/en/1.6/manual/dop/guides/deploy/block-deploy.md
  docs/en/1.6/manual/dop/guides/deploy/config.md
  docs/en/1.6/manual/dop/guides/deploy/deploy-by-cicd-pipeline.md
  docs/en/1.6/manual/dop/guides/deploy/deploy-from-artifact.md
  docs/en/1.6/manual/dop/guides/deploy/management.md
  docs/en/1.6/manual/dop/guides/deploy/release.md
  docs/en/1.6/manual/dop/guides/deploy/resource-management.md
Labels: approved

#164 modify artifact best practice
  docs/.vuepress/sidebar/vers/1.6.js
  docs/1.6/manual/dop/best-practices/release.md
Labels: approved

#170 feat: update example for hmac
  .DS_Store
  docs/1.6/manual/msp/guides/apigw/auth.md
Labels: msp, approved

#172 update cli version for 1.5 doc
  docs/1.5/manual/cli/explain-args.md
  docs/en/1.5/manual/cli/explain-args.md
Labels: approved

#171 fix: modify autoTest docs
  docs/1.6/manual/dop/guides/qa-and-testing/auto-test-getting-started.md
Labels: approved

#173 update cli version for 1.6
  docs/1.6/manual/cli/explain-args.md
  docs/en/1.6/manual/cli/explain-args.md
Labels: approved

#174 feat: custom datetime format
  docs/1.6/manual/dop/guides/reference/pipeline.md
  package-lock.json
Labels: approved

#175 feat: values reference
  docs/1.6/manual/dop/guides/reference/erda-yaml.md
Labels: approved

#177 fix: version lost postfix zero
  docs/.vuepress/nav/en.js
  docs/.vuepress/nav/zh.js
  docs/.vuepress/util.js
Labels: approved

#178 feat: remove {{}}
  docs/2.0/manual/dop/guides/reference/pipeline.md
Labels: dop, approved

#180 update for cli 2.x
  .DS_Store
  docs/.vuepress/sidebar/vers/2.0.js
  docs/2.0/.DS_Store
  docs/2.0/manual/.DS_Store
  docs/2.0/manual/cli/explain-args.md
  docs/2.0/manual/cli/install.md
  docs/2.0/manual/cli/use.md
Labels: approved

#181 update docs
  .gitignore
  docs/.vuepress/sidebar/vers/2.0.js
  docs/2.0/manual/msp/guides/apm/apm-overview.md
  docs/2.0/manual/msp/guides/apm/java-agent-guide.md
  docs/2.0/manual/msp/guides/apm/service-list.md
  docs/2.0/manual/msp/guides/apm/service-monitor.md
  docs/2.0/manual/msp/guides/apm/service-overview.md
  docs/2.0/manual/msp/guides/apm/trace.md
Labels: approved

#184 Feature/msp project init
  docs/2.0/manual/msp/guides/platform/msp-project.md
Labels: msp, approved

#186 feat: add docs for quick start installation
  docs/2.0/manual/install/docker-install.md
Labels: msp, approved

#188 update en doc of docker installation
  docs/.vuepress/sidebar/vers/2.0.js
  docs/en/2.0/manual/install/docker-install.md
Labels: approved

#187 update en version of msp project
  docs/.vuepress/sidebar/vers/2.0-en.js
  docs/en/2.0/manual/msp/guides/apm/apm-overview.md
  docs/en/2.0/manual/msp/guides/apm/java-agent-guide.md
  docs/en/2.0/manual/msp/guides/apm/trace.md
  docs/en/2.0/manual/msp/guides/platform/msp-project.md
Labels: approved

#189 fix cn menu bug
  docs/.vuepress/sidebar/vers/2.0.js
Labels: approved

#193 style: align sidebar menu
  docs/.vuepress/styles/index.styl
Labels: approved

#199 chore: update lock file content
  package-lock.json
Labels: approved
